# Generated by Django 3.1.2 on 2020-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20201031_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
