# Generated by Django 3.1.2 on 2020-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_newuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='pfp',
            field=models.ImageField(blank=True, default='default_pfp', null=True, upload_to=''),
        ),
    ]
