# Generated by Django 3.1.2 on 2020-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20201216_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='pfp',
            field=models.ImageField(blank=True, default='default_pfp.jpg', null=True, upload_to=''),
        ),
    ]
