# Generated by Django 3.1.2 on 2020-12-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201211_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
