# Generated by Django 3.1.2 on 2020-12-12 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created',
            new_name='timeCreated',
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastEdited',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
