# Generated by Django 3.1.2 on 2020-12-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_ticket'),
        ('tickets', '0002_auto_20201211_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='personnel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ticket', to='projects.projectmember'),
        ),
    ]
