# Generated by Django 3.1.2 on 2020-12-12 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_auto_20201212_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
