# Generated by Django 3.1.2 on 2020-12-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='race',
            field=models.CharField(choices=[('Bugs/Errors', 'Bugs/Errors')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=100),
        ),
    ]
