# Generated by Django 3.1.2 on 2020-12-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
